[package]
name = "alchemy_registry"
version.workspace = true
edition.workspace = true

[dependencies]
alchemy_core = { path = "../alchemy_core" }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
sha2 = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
async-trait = "0.1"
tempfile = "3"
