[package]
name = "alchemy_core"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
node-semver = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
petgraph = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
async-trait = "0.1"
glob = { workspace = true }

[dev-dependencies]
tempfile = "3"
